services:
  mov:
    image: valawai/mov:${MOV_TAG:-latest}
    container_name: treatment_demo_mov
    profiles: [mov,all]
    depends_on:
      mongo:
        condition: service_healthy
        restart: true
      mq:
        condition: service_healthy
        restart: true
    ports:
      - ${MOV_UI_PORT:-8080}:8080
    networks:
      - treatment_demo_net
    environment:
      RABBITMQ_HOST: ${MQ_HOST:-mq}
      RABBITMQ_PORT: ${MQ_PORT:-5672}
      RABBITMQ_USERNAME: ${MQ_USER:-mov}
      RABBITMQ_PASSWORD: ${MQ_PASSWORD:-password}
      QUARKUS_MONGODB_DATABASE: ${MOV_DB_NAME:-movDB}
      QUARKUS_MONGODB_CREDENTIALS_USERNAME: ${MOV_DB_USER_NAME:-mov}
      QUARKUS_MONGODB_CREDENTIALS_PASSWORD: ${MOV_DB_USER_PASSWORD:-password}
      QUARKUS_MONGODB_HOSTS: ${DB_HOST:-mongo}:${MONGO_PORT:-27017}
      MOV_UI_URL: http://localhost:${MOV_UI_PORT:-8080}
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -s http://localhost:8080/q/health | grep -m 1 -P \"^[\\s|\\{|\\\"]+status[\\s|\\:|\\\"]+.+\\\"\" |grep -q \"\\\"UP\\\"\"",
        ]
      interval: 1m
      timeout: 10s
      retries: 5
      start_period: 1m
      start_interval: 5s

  mq:
    image: rabbitmq:${RABBITMQ_TAG:-management}
    container_name: treatment_demo_mq
    profiles: [mov,all]
    hostname: ${MQ_HOST:-mq}
    ports:
      - ${MQ_LOCAL_PORT:-5672}:5672
      - ${MQ_LOCAL_UI_PORT:-8081}:15672
    networks:
      - treatment_demo_net
    environment:
      RABBITMQ_DEFAULT_USER: ${MQ_USER:-mov}
      RABBITMQ_DEFAULT_PASS: ${MQ_PASSWORD:-password}
    healthcheck:
      test: ["CMD-SHELL", "rabbitmq-diagnostics -q ping"]
      interval: 1m
      timeout: 10s
      retries: 5
      start_period: 1m
      start_interval: 5s

  mongo:
    image: mongo:${MONGODB_TAG:-latest}
    container_name: treatment_demo_mongo
    profiles: [mov,all]
    hostname: ${DB_HOST:-mongo}
    ports:
      - ${MONGO_LOCAL_PORT:-27017}:27017
    networks:
      - treatment_demo_net
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USER:-root}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD:-password}
      MONGO_INITDB_DATABASE: ${DB_NAME:-movDB}
      MOV_DB_NAME: ${MOV_DB_NAME:-movDB}
      MOV_DB_USER_NAME: ${MOV_DB_USER_NAME:-mov}
      MOV_DB_USER_PASSWORD: ${MOV_DB_USER_PASSWORD:-password}
    volumes:
      - ${MONGO_LOCAL_DATA:-~/.mongo_data/treatment_demo_db}:/data/db
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "mongosh --quiet localhost/${DB_NAME:-movDB} --eval 'quit(db.runCommand({ ping: 1 }).ok ? 0 : 2)'",
        ]
      interval: 1m
      timeout: 10s
      retries: 5
      start_period: 1m
      start_interval: 5s
    configs:
      - source: initialize-movDB.js
        target: /docker-entrypoint-initdb.d/init-mongo.js

  pg:
    image: postgres:${POSTGRES_TAG:-17}
    container_name: treatment_demo_C0_pg
    profiles: [C0, all]
    ports:
      - ${PG_PORT:-5432}:5432
    networks:
      - treatment_demo_net
    environment:
      POSTGRES_USER: ${PG_USER_NAME:-c0_patient_treatment_ui}
      POSTGRES_PASSWORD: ${PG_USER_PASSWORD:-password}
      POSTGRES_DB: ${PG_DB_NAME:-c0_patient_treatment_ui_db}
    volumes:
      - ${PG_LOCAL_DATA:-~/.pg_data/treatment_demo_db}:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 1m
      timeout: 10s
      retries: 5
      start_period: 1m
      start_interval: 5s

  patient_treatment_ui:
    image: valawai/c0_patient_treatment_ui:${C0_PATIENT_TREATMENT_UI_TAG:-latest}
    container_name: treatment_demo_c0_component
    profiles: [C0, all]
    networks:
      - treatment_demo_net
    ports:
      - ${C0_PATIENT_TREATMENT_UI_PORT:-8082}:8080
    depends_on:
      pg:
        condition: service_healthy
        restart: true
      mov:
        condition: service_healthy
        required: false
    environment:
      RABBITMQ_HOST: ${MQ_HOST:-mq}
      RABBITMQ_PORT: ${MQ_PORT:-5672}
      RABBITMQ_USERNAME: ${MQ_USER:-mov}
      RABBITMQ_PASSWORD: ${MQ_PASSWORD:-password}
      C0_PATIENT_TREATMENT_UI_URL: http://localhost:${C0_PATIENT_TREATMENT_UI_PORT:-8082}
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -s http://localhost:8080/q/health | grep -m 1 -P \"^[\\s|\\{|\\\"]+status[\\s|\\:|\\\"]+.+\\\"\" |grep -q \"\\\"UP\\\"\"",
        ]
      interval: 1m
      timeout: 10s
      retries: 5
      start_period: 1m
      start_interval: 5s

  nit_protocol_manager:
    image: valawai/c1_nit_protocol_manager:${C1_NIT_PROTOCOL_MANAGER_TAG:-latest}
    container_name: treatment_demo_c1_component
    profiles: [C1, all]
    depends_on:
      mov:
        condition: service_healthy
        required: false
    networks:
      - treatment_demo_net
    environment:
      RABBITMQ_HOST: ${MQ_HOST:-mq}
      RABBITMQ_PORT: ${MQ_PORT:-5672}
      RABBITMQ_USERNAME: ${MQ_USER:-mov}
      RABBITMQ_PASSWORD: ${MQ_PASSWORD:-password}
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -s http://localhost:8080/q/health | grep -m 1 -P \"^[\\s|\\{|\\\"]+status[\\s|\\:|\\\"]+.+\\\"\" |grep -q \"\\\"UP\\\"\"",
        ]
      interval: 1m
      timeout: 10s
      retries: 5
      start_period: 1m
      start_interval: 5s

  treatment_autonomy_valuator:
    image: valawai/c2_treatment_autonomy_valuator:${C2_TREATMENT_AUTONOMY_VALUATOR_TAG:-latest}
    container_name: treatment_demo_c2_component_autonomy
    profiles: [C2, all]
    depends_on:
      mov:
        condition: service_healthy
        required: false
    networks:
      - treatment_demo_net
    environment:
      RABBITMQ_HOST: ${MQ_HOST:-mq}
      RABBITMQ_PORT: ${MQ_PORT:-5672}
      RABBITMQ_USERNAME: ${MQ_USER:-mov}
      RABBITMQ_PASSWORD: ${MQ_PASSWORD:-password}
      LOG_CONSOLE_LEVEL: ${LOG_LEVEL:-INFO}
    healthcheck:
      test: ["CMD-SHELL", "test -s /app/logs/component_id.json"]
      interval: 1m
      timeout: 10s
      retries: 5
      start_period: 1m
      start_interval: 5s

  treatment_beneficence_valuator:
    image: valawai/c2_treatment_beneficence_valuator:${C2_TREATMENT_BENEFICENCE_VALUATOR_TAG:-latest}
    container_name: treatment_demo_c2_component_beneficence
    profiles: [C2, all]
    depends_on:
      mov:
        condition: service_healthy
        required: false
    networks:
      - treatment_demo_net
    environment:
      RABBITMQ_HOST: ${MQ_HOST:-mq}
      RABBITMQ_PORT: ${MQ_PORT:-5672}
      RABBITMQ_USERNAME: ${MQ_USER:-mov}
      RABBITMQ_PASSWORD: ${MQ_PASSWORD:-password}
      LOG_CONSOLE_LEVEL: ${LOG_LEVEL:-INFO}
    healthcheck:
      test: ["CMD-SHELL", "test -s /app/logs/component_id.json"]
      interval: 1m
      timeout: 10s
      retries: 5
      start_period: 1m
      start_interval: 5s

  treatment_justice_valuator:
    image: valawai/c2_treatment_justice_valuator:${C2_TREATMENT_JUSTICE_VALUATOR_TAG:-latest}
    container_name: treatment_demo_c2_component_justice
    profiles: [C2, all]
    depends_on:
      mov:
        condition: service_healthy
        required: false
    networks:
      - treatment_demo_net
    environment:
      RABBITMQ_HOST: ${MQ_HOST:-mq}
      RABBITMQ_PORT: ${MQ_PORT:-5672}
      RABBITMQ_USERNAME: ${MQ_USER:-mov}
      RABBITMQ_PASSWORD: ${MQ_PASSWORD:-password}
      LOG_CONSOLE_LEVEL: ${LOG_LEVEL:-INFO}
    healthcheck:
      test: ["CMD-SHELL", "test -s /app/logs/component_id.json"]
      interval: 1m
      timeout: 10s
      retries: 5
      start_period: 1m
      start_interval: 5s

  treatment_nonmaleficence_valuator:
    image: valawai/c2_treatment_nonmaleficence_valuator:${C2_TREATMENT_NONMALEFICENCE_VALUATOR_TAG:-latest}
    container_name: treatment_demo_c2_component_nonmaleficence
    profiles: [C2, all]
    depends_on:
      mov:
        condition: service_healthy
        required: false
    networks:
      - treatment_demo_net
    environment:
      RABBITMQ_HOST: ${MQ_HOST:-mq}
      RABBITMQ_PORT: ${MQ_PORT:-5672}
      RABBITMQ_USERNAME: ${MQ_USER:-mov}
      RABBITMQ_PASSWORD: ${MQ_PASSWORD:-password}
      LOG_CONSOLE_LEVEL: ${LOG_LEVEL:-INFO}
    healthcheck:
      test: ["CMD-SHELL", "test -s /app/logs/component_id.json"]
      interval: 1m
      timeout: 10s
      retries: 5
      start_period: 1m
      start_interval: 5s

networks:
  treatment_demo_net:

configs:
  initialize-movDB.js:
    content: |
      db.createUser({
          user: process.env.MOV_DB_USER_NAME,
          pwd: process.env.MOV_DB_USER_PASSWORD,
          roles: [{
              role: 'readWrite',
              db: process.env.MOV_DB_NAME
          }]
      })
